### ISSUE TITLE
Bootstrap 100% width

### ISSUE THREAD

**Issue by rosskevin** [Bluefieldscom/intl-tel-input#270]
On my bootstrap setup, I've added:

```css
.intl-tel-input {
  display: table-cell;
  width: 100%;
}
```

Which seem to be recognized by the browser as indicated by the inspector, but the width on the phone input field remains constrained on Chrome, Firefox, and Safari.  I don't see any reason for the width to be constrained in the inspector for Chrome or Firefox.

What am I missing?

![dummy](https://cloud.githubusercontent.com/assets/136564/9358806/8be30952-4653-11e5-8216-72ed7d8e826c.png)
